language: node_js
dist: trusty
git:
  depth: false

node_js:
  - '12'

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  allow_failures:
    - script: ./scripts/ci/setup-npm.sh
    - script: ./scripts/ci/release-npm-next-tag.sh
  include:
    - stage: 'Test'
      script:
        - yarn test
        - cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | ${TRAVIS_BUILD_DIR}/node_modules/.bin/coveralls
    - stage: 'Build and Deploy'
      before_script:
        - git checkout ${TRAVIS_BRANCH}
        - bash ./scripts/ci/version-bump-rc.sh
      script: yarn build
      before_deploy:
        - bash ./scripts/ci/setup-npm.sh
      deploy:
        - provider: script
          script: bash ./scripts/ci/release-npm-next-tag.sh
          skip_cleanup: true
          on:
            branch: master
