name: build

on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: 'Install, Test & Build'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      CI: true

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: yarn install
    - name: run tests
      run: yarn test --runInBand
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: build project
      run: yarn build
