name: build

on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: 'Install, Test & Build'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        react-version: [16.8.0, 16.14.0, ^17.0.0]

    env:
      CI: true

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node.js
      uses: actions/setup-node@v2.1.3
      with:
        node-version: 14
    - name: install dependencies - React ${{ matrix.react-version }}
      run: |
        node --experimental-json-modules scripts/ci/set-react-resolution.mjs ${{ matrix.react-version }}
        yarn install
    - name: run tests
      run: yarn test --runInBand
    - name: Coveralls
      # only collect coverage information on latest react version
      if: matrix.react-version == '^17.0.0'
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: build project
      run: yarn build
