name: seed-ci

on:
  push:
    paths:
      - packages/cra-template-seed/**/*
  pull_request:
    paths:
      - packages/cra-template-seed/**/*

jobs:
  build:
    name: 'Install, Test & Build'
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: create new project
        run: |
          yarn create react-app seed-ci-test --template file:./packages/cra-template-seed
      - name: run tests
        run: |
          cd seed-ci-test
          yarn test:coverage
        env:
          SKIP_PREFLIGHT_CHECK: true
      - name: build project
        run: |
          cd seed-ci-test
          yarn build
        env:
          SKIP_PREFLIGHT_CHECK: true
